// Copyright Epic Games, Inc. All Rights Reserved.
// Copyright (c) 2025 Damian Nowakowski. All rights reserved.

/**
 * Because the SGraphPinText and FEditableTextGraphPin are private, we have no other option but
 * copy those classes and add our changes to provide preview under the
 * FText pins in BP nodes.
 * If at any point those classes become public, it should be rewritten
 * to just inherit from them.
 */

#if ELTEDITOR_WITH_PREVIEW_IN_UI

#include "SGraphPinTextPreview.h"
#include "ScopedTransaction.h"
#include "STextPropertyEditableTextBox.h"

class FEditableTextPreviewGraphPin : public IEditableTextProperty
{
public:
	FEditableTextPreviewGraphPin(UEdGraphPin* InGraphPinObj)
		: GraphPinObjRef(InGraphPinObj)
	{
	}

	virtual bool IsMultiLineText() const override
	{
		return true;
	}

	virtual bool IsPassword() const override
	{
		return false;
	}

	virtual bool IsReadOnly() const override
	{
		if (const UEdGraphPin* GraphPinObj = GraphPinObjRef.Get())
		{
			return GraphPinObj->bDefaultValueIsReadOnly;
		}

		return false;
	}

	virtual bool IsDefaultValue() const override
	{
		if (const UEdGraphPin* GraphPinObj = GraphPinObjRef.Get())
		{
			FString TextAsString;
			FTextStringHelper::WriteToBuffer(TextAsString, GraphPinObj->DefaultTextValue);
			return TextAsString.Equals(GraphPinObj->AutogeneratedDefaultValue, ESearchCase::CaseSensitive);
		}

		return false;
	}

	virtual FText GetToolTipText() const override
	{
		return FText::GetEmpty();
	}

	virtual int32 GetNumTexts() const override
	{
		return 1;
	}

	virtual FText GetText(const int32 InIndex) const override
	{
		check(InIndex == 0);
		if (const UEdGraphPin* GraphPinObj = GraphPinObjRef.Get())
		{
			return GraphPinObj->DefaultTextValue;
		}

		return FText::GetEmpty();
	}

	virtual void SetText(const int32 InIndex, const FText& InText) override
	{
		check(InIndex == 0);
		if (UEdGraphPin* GraphPinObj = GraphPinObjRef.Get())
		{
			const FScopedTransaction Transaction(NSLOCTEXT("GraphEditor", "ChangeTxtPinValue", "Change Text Pin Value"));
			GraphPinObj->Modify();
			GraphPinObj->GetSchema()->TrySetDefaultText(*GraphPinObj, InText);
		}
	}

	virtual bool IsValidText(const FText& InText, FText& OutErrorMsg) const override
	{
		return true;
	}

#if USE_STABLE_LOCALIZATION_KEYS
	virtual void GetStableTextId(const int32 InIndex, const ETextPropertyEditAction InEditAction, const FString& InTextSource, const FString& InProposedNamespace, const FString& InProposedKey, FString& OutStableNamespace, FString& OutStableKey) const override
	{
		check(InIndex == 0);
		if (const UEdGraphPin* GraphPinObj = GraphPinObjRef.Get())
		{
			StaticStableTextId(GraphPinObj->GetOwningNodeUnchecked(), InEditAction, InTextSource, InProposedNamespace, InProposedKey, OutStableNamespace, OutStableKey);
		}
	}
#endif // USE_STABLE_LOCALIZATION_KEYS

private:
	FEdGraphPinReference GraphPinObjRef;
};

ELTEDITOR_PRAGMA_DISABLE_OPTIMIZATION

void SGraphPinTextPreview::Construct(const FArguments& InArgs, UEdGraphPin* InGraphPinObj)
{
	SGraphPin::Construct(SGraphPin::FArguments(), InGraphPinObj);
}

TSharedRef<SWidget>	SGraphPinTextPreview::GetDefaultValueWidget()
{
	// We need to use SVerticalBox here to be able to show both the editable text box and the preview text below it.
	return SNew(SVerticalBox)
		+SVerticalBox::Slot()
		.AutoHeight()
		.Padding(0.f, 6.f)
		[
			// This is the original SNew from SGraphPinText, but we display it alongside with the preview text,
			// so we can see the changes in real time.
			SNew(STextPropertyEditableTextBox, MakeShareable(new FEditableTextPreviewGraphPin(GraphPinObj)))
				.Style(FAppStyle::Get(), "Graph.EditableTextBox")
				.Visibility(this, &SGraphPin::GetDefaultValueVisibility)
				.ForegroundColor(FSlateColor::UseForeground())
				.IsEnabled(this, &SGraphPin::GetDefaultValueIsEditable)
				.WrapTextAt(400.0f)
				.MinDesiredWidth(18.0f)
				.MaxDesiredHeight(200.0f)
		]
		+SVerticalBox::Slot()
		.AutoHeight()
		[
			// Display the localized text value as a text block under the editable text box.
			SNew(STextBlock).Text_Lambda([this]
			{
				if (GraphPinObj)
				{
					return GraphPinObj->DefaultTextValue;
				}
				return FText::GetEmpty();
			})
		];
}

ELTEDITOR_PRAGMA_ENABLE_OPTIMIZATION

#endif //ELTEDITOR_WITH_PREVIEW_IN_UI

